const sections=[['home','⌂','MERKEZ'],['workers','◇','ÇALIŞANLAR'],['missions','◎','GÖREVLER'],['approvals','!','ONAYLAR'],['youtube','▷','YOUTUBE'],['finance','◈','FİNANS'],['research','⌕','ARAŞTIRMA'],['aiProviders','◉','AI SAĞLAYICILARI'],['costs','¤','MALİYETLER'],['systemLogs','≡','SİSTEM / LOGLAR'],['settings','⚙','AYARLAR']];
document.querySelector('main').insertAdjacentHTML('beforeend',`<section id="research" class="view"><div class="page-title"><div><small>GERÇEK MISSION KAYITLARI</small><h2>Araştırma Merkezi</h2></div></div><div id="researchCards" class="cards"></div></section><section id="aiProviders" class="view"><div class="page-title"><div><small>AVAILABILITY · EXECUTION HISTORY</small><h2>AI Sağlayıcıları</h2></div></div><div id="providerCards" class="cards workforce-grid"></div></section><section id="costs" class="view"><div class="page-title"><div><small>YALNIZCA ÖLÇÜLEN MALİYET</small><h2>Maliyetler</h2></div></div><div id="costCards" class="cards"></div></section><section id="systemLogs" class="view"><div class="page-title"><div><small>SANITIZED OPERATIONS</small><h2>Sistem / Loglar</h2></div></div><div id="logCards" class="timeline"></div></section>`);
let latest={},shownNotifications=new Set(),technicalLogs=false,lastMark=0;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('nav').innerHTML=sections.map(([id,icon,name],i)=>`<button data-view="${id}" class="${i?'':'active'}"><i>${icon}</i><span>${name}</span></button>`).join('');
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view,[data-view]').forEach(x=>x.classList.remove('active'));$(b.dataset.view).classList.add('active');b.classList.add('active');if(b.dataset.view==='youtube')loadYoutubeArtifacts();if(b.dataset.view==='workers')loadProviders();if(['research','aiProviders','costs','systemLogs'].includes(b.dataset.view))loadObservability(b.dataset.view)});
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3800)}
async function api(path,body){const options=body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)};const response=await fetch(path,options),value=await response.json();if(!response.ok)throw Error(value.error||response.statusText);return value}
function cards(id,rows,render){$(id).innerHTML=rows?.length?rows.map(render).join(''):'<p class="empty">Henüz gerçek kayıt yok.</p>'}
const pct=x=>x==null?'—':(Number(x)*100).toFixed(2)+'%',money=x=>x==null?'—':new Intl.NumberFormat('tr-TR',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(x),num=x=>x==null?'—':new Intl.NumberFormat('tr-TR',{maximumFractionDigits:4}).format(x);
function notifyBrowser(rows){if(!('Notification'in window)||Notification.permission!=='granted')return;rows.filter(x=>!x.read&&!shownNotifications.has(x.id)).forEach(x=>{shownNotifications.add(x.id);new Notification(`JARVIS · ${x.type}`,{body:x.message,tag:x.id})})}
function metric(label,value,help=''){return `<div class="metric"><label>${label}</label><strong>${esc(value)}</strong>${help?`<small>${esc(help)}</small>`:''}</div>`}
function render(state){latest=state;const active=state.active_mission,performance=state.finance_performance?.paper||{},pending=state.approvals.filter(x=>x.status==='PENDING').length;
  $('currentTime').textContent=new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'medium',timeZone:'Europe/Berlin'}).format(new Date())+' · Europe/Berlin';
  $('backendKpi').textContent=state.health?.backend_alive?'ONLINE':'OFFLINE';$('healthDetail').textContent=`Runtime ${state.health?.runtime_state||'—'} · ${state.health?.notifications?.unread||0} unread`;
  $('coreState').textContent=$('coreKpi').textContent=state.core.state;$('coreState').dataset.state=state.core.state;
  $('activeGoal').textContent=active?.goal||'Yeni görev bekleniyor';$('missionStatus').textContent=active?.status||'BEKLİYOR';$('missionReason').textContent=active?'Görev gerçek Jarvis pipeline içinde ilerliyor.':'Bir görev verdiğinde nedenini, aşamasını ve sonucunu burada göreceksin.';
  $('stage').textContent=$('stageKpi').textContent=active?.stage||'—';$('worker').textContent=active?.worker||'—';$('workerKpi').textContent=active?.worker||'Atanmış worker yok';$('approvalKpi').textContent=pending;const hasPaperData=(state.paper.positions||[]).length+(state.paper.closed||[]).length>0;$('pnlKpi').textContent=hasPaperData?money((state.paper.cash||0)-(state.paper.initial_cash||0)):'Henüz veri yok';
  const progress=Math.round(active?.progress||0);$('progress').style.width=progress+'%';$('progressText').textContent=progress+'%';
  const activities=technicalLogs?state.activities:state.activities.filter(x=>['UNDERSTANDING','COMPLETED','BLOCKED','VALIDATION'].includes(x.stage)||x.level!=='info');
  cards('activity',activities,x=>`<div class="event ${esc(x.level)}"><span>${new Date(x.time).toLocaleTimeString('tr-TR')}</span><b>${esc(x.stage)} ${esc(x.worker)}</b><p>${esc(x.message)}</p></div>`);
  cards('notifications',state.notifications,x=>`<div class="notice ${x.read?'read':''}"><i></i><div><b>${esc(x.type)}</b><p>${esc(x.message)}</p><small>${new Date(x.created_at).toLocaleString('tr-TR')}</small></div></div>`);notifyBrowser(state.notifications);
  cards('missionsList',state.missions,x=>`<article><div class="section-head"><label>${esc(x.status)} · ${esc(x.stage)}</label><span class="badge">${Math.round(x.progress||0)}%</span></div><h3>${esc(x.goal)}</h3><p><b>Sonuç:</b> ${esc(x.result||x.error||'Sonuç bekleniyor')}</p>${x.artifacts?.length?`<p><b>Kanıt:</b> ${x.artifacts.map(esc).join(', ')}</p>`:''}</article>`);
  const youtubeRows=[...(active&&active.source==='youtube_queue'?[{...active,current:true}]:[]),...(state.engines.youtube.queue||[])];cards('youtubeData',youtubeRows,x=>`<article><label>${esc(x.status)} · ${x.current?'CURRENT MISSION':'QUEUE'}</label><h3>${esc(x.goal)}</h3><p>Progress: ${Math.round(x.progress||0)}% · ${esc(x.stage||'QUEUED')}</p><p>${new Date(x.created_at).toLocaleString('tr-TR')}</p></article>`);
  const yl=state.youtube_learning||{}, productions=yl.productions||[];
  const wf=state.workforce||{}, workers=wf.workers||[], ws=wf.summary||{};
  const accounts=state.accounts||[];
  cards('accountCards',workers.filter(w=>w.division==='YOUTUBE'),w=>{const a=accounts.find(x=>x.assigned_worker_id===w.worker_id);return `<article><label>${esc(w.name)} · ${esc(w.channel_id)}</label><h3>${esc(a?.connection_status||'NOT CONNECTED')}</h3><p>Channel: ${esc(a?.channel_title||'—')}<br>Authorization: ${esc(a?.provider||'GOOGLE YOUTUBE OAUTH')}<br>Last verified: ${esc(a?.last_verified_at||'—')}<br>Health: ${esc(a?.connection_status||'READY TO CONNECT')}</p><div class="actions">${a?`<button onclick="accountAction('${a.account_id}','verify')">VERIFY CHANNEL</button><button onclick="accountAction('${a.account_id}','disconnect')">DISCONNECT</button>`:`<button class="primary" onclick="connectAccount('${w.worker_id}')">CONNECT ACCOUNT</button>`}</div><small>Schedules remain disabled until explicitly enabled.</small></article>`});
  $('workforceSummary').innerHTML=['active','idle','blocked','paused'].map(k=>`<article><label>${k.toUpperCase()}</label><strong>${esc(ws[k]||0)}</strong></article>`).join('');
  cards('workforceCards',workers,w=>`<article class="worker-card"><div class="section-head"><label>${esc(w.division||w.department)}</label><span class="badge ${w.status==='working'?'safe':''}">${esc(w.status)}</span></div><h3>${esc(w.name)}</h3><p>${esc(w.role)}</p><p><b>Mevcut görev:</b> ${esc(w.current_task||'Henüz veri yok')}</p><p><b>Provider:</b> ${esc(w.provider||'Henüz veri yok')} · <b>Model:</b> ${esc(w.model||'Henüz veri yok')}</p><p><b>Son çalışma:</b> ${esc(w.last_run_at||'Henüz veri yok')} · <b>Sonuç:</b> ${w.last_success==null?'Henüz veri yok':w.last_success?'Başarılı':'Başarısız'}</p></article>`);
  cards('youtubeHistory',[...productions].reverse(),x=>{const thumb=x.artifact?.thumbnail_path?'/artifact/'+encodeURI(x.artifact.thumbnail_path.replace(/^workspace[\\/]/,'')):'';return `<article>${thumb?`<img src="${thumb}" alt="${esc(x.topic)} thumbnail">`:''}<label>${esc(x.quality?.production_readiness?'READY':'FAILED')} · ${esc(x.created_at)}</label><h3>${esc(x.topic)}</h3><div class="metric-grid"><div class="metric">Quality<strong>${esc(x.quality?.overall??'—')}</strong></div><div class="metric">Motion<strong>${esc(x.quality?.motion??'—')}</strong></div><div class="metric">Story<strong>${esc(x.quality?.story??'—')}</strong></div><div class="metric">Audio<strong>${esc(x.quality?.audio??'—')}</strong></div><div class="metric">Character<strong>${esc(x.quality?.character_consistency??'—')}</strong></div></div></article>`});
  cards('youtubeLearning',productions.length?[productions[productions.length-1]]:[],x=>{const prev=productions.length>1?productions[productions.length-2]:null;const changed=prev?Object.keys(x.fingerprints||{}).filter(k=>x.fingerprints[k]!==prev.fingerprints?.[k]):[];return `<article><label>WHAT WORKED</label><p>${esc((x.learning?.what_worked||[]).join(' · ')||'No validated pattern yet')}</p><label>WHAT CHANGED</label><p>${esc(changed.join(' · ')||'First production baseline')}</p><label>FAILURE REASONS</label><p>${esc((x.failure?.rejection_reasons||[]).join(' · ')||'None')}</p><label>NEXT PRODUCTION CHANGES</label><p>${esc((yl.next_production_changes||[]).join(' · '))}</p></article>`});
  cards('youtubeCharacters',Object.values(yl.characters||{}),x=>`<article><label>RECURRING CHARACTER</label><h3>${esc(x.name)}</h3><p>${esc(JSON.stringify(x.canonical_appearance||x))}</p><p>Successful poses: ${esc((x.successful_poses||[]).join(', ')||'—')}</p><p>Known failures: ${esc((x.failed_poses||[]).join(', ')||'—')}</p></article>`);
  cards('youtubeExperiments',[...(yl.experiments||[])].reverse(),x=>`<article><label>${esc(x.result)}</label><p>${esc(x.tested_variation)}</p></article>`);
  cards('youtubeAnalytics',[yl.analytics||{source:'NOT_CONNECTED'}],x=>`<article><label>YOUTUBE ANALYTICS</label><h3>${esc((x.source||'NOT_CONNECTED').replace('_',' '))}</h3><p>Official analytics bağlı değilse performans metrikleri üretilmez.</p></article>`);
  cards('positions',state.paper.positions,x=>`<article class="trade"><div class="section-head"><label>${esc(x.label)}</label><span class="badge safe">${esc(x.status)}</span></div><h3>${esc(x.asset)} · ${esc(x.direction)}</h3><div class="metric-grid">${metric('Entry',num(x.entry))}${metric('Şimdi',num(x.current_price))}${metric('Stop',num(x.stop))}${metric('Target',num(x.target))}${metric('P&L',money(x.unrealized_pnl))}${metric('MAE / MFE',`${pct(x.max_adverse_excursion)} / ${pct(x.max_favorable_excursion)}`)}</div><p>Strateji: ${esc(x.strategy)} · Rejim: ${esc(x.market_regime)} · Güven: ${pct(x.confidence)}</p><button onclick="closePaper('${x.id}')">PAPER POZİSYONU KAPAT</button></article>`);
  cards('closedTrades',state.paper.closed.slice().reverse().slice(0,20),x=>`<article class="trade"><label>PAPER CLOSED · ${esc(x.reason)}</label><h3>${esc(x.asset)} · <span class="${x.pnl>=0?'positive':'negative'}">${money(x.pnl)} (${pct(x.pnl_percent)})</span></h3><p>Entry ${num(x.entry)} → Exit ${num(x.exit)} · Ücret ${money(x.fees)}</p><p>${esc(x.strategy)} · ${esc(x.market_regime)} · MAE ${pct(x.max_adverse_excursion)} · MFE ${pct(x.max_favorable_excursion)}</p></article>`);
  const qualification=state.engines.finance.qualification;cards('financeData',[...(qualification?[qualification]:[]),...state.backtests.slice(0,8)],x=>x.evidence?`<article><label>${esc(x.label)}</label><h3>${x.qualified?'QUALIFIED':'KANIT TOPLANIYOR'}</h3><p>${esc(x.reasons.join(' · ')||'Qualification kanıtları tamamlandı; live yine devre dışı.')}</p><p>Overfitting riski: <b>${esc(x.overfitting_risk)}</b></p></article>`:`<article><label>${esc(x.label)}</label><h3>${esc(x.asset)} · ${esc(x.strategy)}</h3><div class="metric-grid">${metric('Net getiri',pct(x.net_return_after_costs))}${metric('Drawdown',pct(x.max_drawdown))}${metric('İşlem',x.trade_count??x.trades)}${metric('Win rate',pct(x.win_rate))}${metric('Profit factor',num(x.profit_factor))}${metric('OOS işlem',x.out_of_sample_metrics?.trade_count??0)}</div><p>${esc(x.regime)} · ${esc(x.source)}</p></article>`);
  cards('approvalList',state.approvals,x=>`<article class="approval"><div class="section-head"><label>${esc(x.type)} · ${esc(x.status)}</label><span class="badge risk">${esc(x.risk)}</span></div><h3>${esc(x.what)}</h3><p><b>Neden?</b> ${esc(x.why)}</p><p><b>Risk:</b> ${esc(x.risk)} · <b>Maksimum maliyet:</b> ${esc(x.cost??'Belirtilmedi')}</p><p><b>Beklenen:</b> ${esc(x.expected_result??'Belirtilmedi')}</p>${x.decided_at?`<p><b>Karar:</b> ${esc(x.decision_reason)} · ${esc(x.decided_at)}</p>`:''}${x.type==='finance_real_trade'?'<p class="negative"><b>GERÇEK EMİR EXECUTION DEVRE DIŞI.</b> Onay yalnız karar kaydıdır.</p>':''}${x.status==='PENDING'?`<label for="reason-${x.id}">KARAR GEREKÇESİ</label><input id="reason-${x.id}" class="decision-reason" maxlength="1000" placeholder="Kısa gerekçe"><div class="actions"><button class="approve" onclick="decision('${x.id}','approve')">ONAYLA</button><button onclick="decision('${x.id}','request-changes')">DEĞİŞİKLİK İSTE</button><button class="reject" onclick="decision('${x.id}','reject')">REDDET</button></div>`:''}</article>`);
  const p=state.finance_performance?.paper||{};cards('performanceData',[{type:'PAPER',...p},...state.backtests.slice(0,6).map(x=>({type:'BACKTEST',...x}))],x=>`<article><label>${esc(x.type)} · LIVE DEĞİL</label><h3>${x.asset?esc(x.asset):'Paper Portföy'}</h3><div class="metric-grid">${metric('Net getiri',pct(x.net_return_after_costs))}${metric('Drawdown',pct(x.max_drawdown))}${metric('Win rate',pct(x.win_rate))}${metric('Profit factor',num(x.profit_factor))}${metric('Expectancy',num(x.expectancy))}${metric('Sharpe',num(x.sharpe))}${metric('Ort. kazanç',money(x.average_win))}${metric('En büyük kayıp',money(x.largest_loss))}${metric('Kayıp serisi',x.consecutive_losses??0)}</div></article>`);
  const exploration=state.finance_exploration||{},learned=exploration.last_learning;
  const financeHistory=Object.values(exploration.candidates||{}).map(x=>({finance:true,...x}));
  cards('history',[...(learned?[{learning:true,...learned}]:[]),...financeHistory,...state.provider_history],x=>x.learning?`<article><label>FINANCE LEARNING · ${esc(x.learned_at)}</label><h3>${x.qualified} qualified · ${x.rejected} rejected</h3><p>${esc((x.next_exploration||[]).join(' · ')||'Yeni arama alanı bekleniyor')}</p></article>`:x.finance?`<article><label>${esc(x.baseline_or_new)} · ${esc(x.last_tested_at)}</label><h3>${esc(x.name)} · ${esc(x.qualification_result)}</h3><p>${esc((x.rejection_reasons||[]).join(' · ')||x.paper_status)}</p><p>${esc((x.assets_tested||[]).join(', '))} · ${esc((x.timeframes_tested||[]).join(', '))} · ${esc((x.regimes_tested||[]).join(', '))}</p></article>`:`<article><label>${esc(x.recorded_at)}</label><h3>${esc(x.provider)}</h3><p>${esc(x.task_type)} · ${esc(x.duration_seconds)} sn · ${x.success?'Başarılı':'Başarısız'}</p></article>`);
}
async function refresh(){try{const [state,dashboard,workers]=await Promise.all([api('/api/status'),api('/api/dashboard'),api('/api/workers')]);state.workforce={...state.workforce,workers,summary:{active:workers.filter(x=>x.status==='working').length,idle:workers.filter(x=>x.status==='idle').length,blocked:0,paused:0}};render(state);$('coreState').textContent=dashboard.system_status}catch(e){$('coreState').textContent=$('coreKpi').textContent=$('backendKpi').textContent='OFFLINE';$('coreState').dataset.state='STOPPED';$('healthDetail').textContent='Backend yanıt vermiyor';toast(e.message)}}
async function command(source='text'){try{await api('/api/command',{goal:$('goal').value,source});$('goal').value='';toast('Görev gerçek Jarvis pipeline’a gönderildi.')}catch(e){toast(e.message)}}
$('send').onclick=()=>command();document.querySelectorAll('[data-control]').forEach(b=>b.onclick=async()=>{try{await api('/api/control/'+b.dataset.control,{});refresh()}catch(e){toast(e.message)}});
$('toggleLogs').onclick=()=>{technicalLogs=!technicalLogs;$('toggleLogs').textContent=technicalLogs?'ÖZET AKIŞ':'TEKNİK LOG';render(latest)};
$('enableNotifications').onclick=async()=>{if(!('Notification'in window))return toast('Bu browser notification desteklemiyor.');const permission=await Notification.requestPermission();toast(permission==='granted'?'Browser bildirimleri açıldı.':'Bildirim izni verilmedi.')};
$('testNotification').onclick=async()=>{try{await api('/api/notifications/test',{});await refresh();toast('Test bildirimi kaydedildi.')}catch(e){toast(e.message)}};
$('readNotifications').onclick=async()=>{try{await api('/api/notifications/read',{});refresh()}catch(e){toast(e.message)}};
window.decision=async(id,action)=>{try{const reason=$('reason-'+id)?.value||'';await api(`/api/approvals/${id}/${action}`,{reason});toast('Decision recorded: '+action);refresh()}catch(e){toast(e.message)}};
window.closePaper=async id=>{try{await api('/api/finance/close',{position_id:id,reason:'MANUAL'});refresh()}catch(e){toast(e.message)}};
$('youtubeQueue').onclick=async()=>{try{await api('/api/youtube/queue',{goal:$('youtubeGoal').value});$('youtubeGoal').value='';refresh()}catch(e){toast(e.message)}};$('youtubeRun').onclick=async()=>{try{await api('/api/youtube/run-next',{});refresh()}catch(e){toast(e.message)}};
$('backtest').onclick=async()=>{try{toast('Official OHLCV ile backtest çalışıyor…');await api('/api/finance/backtest',{asset:$('asset').value});refresh()}catch(e){toast(e.message)}};
$('marketPaper').onclick=async()=>{try{const x=await api('/api/finance/paper',{asset:$('asset').value});toast(x.direction==='NO_TRADE'?'Strateji şu anda işlem sinyali üretmedi.':'Paper pozisyon açıldı; gerçek emir gönderilmedi.');refresh()}catch(e){toast(e.message)}};
$('markPaper').onclick=async()=>{try{await api('/api/finance/mark',{});lastMark=Date.now();toast('Paper pozisyonlar gerçek piyasa ile güncellendi.');refresh()}catch(e){toast(e.message)}};
$('qualify').onclick=async()=>{try{const q=await api('/api/finance/qualification',{});toast(q.qualified?'Qualification kanıtları tamamlandı; live hâlâ kapalı.':q.reasons.join(' · '));refresh()}catch(e){toast(e.message)}};
$('marketScan').onclick=async()=>{try{const x=await api('/api/finance/market?asset='+encodeURIComponent($('asset').value));$('marketData').innerHTML=metric(x.symbol,num(x.price),x.source)+metric('24s değişim',pct(x.change_percent_24h/100))+metric('24s hacim',num(x.volume_24h))+metric('Volatilite',pct(x.volatility_1h_annualized))+metric('Funding',x.derivatives?pct(x.derivatives.funding_rate):'Yok')+metric('Open interest',x.derivatives?num(x.derivatives.open_interest):'Yok');toast('Official piyasa verisi güncellendi.')}catch(e){toast(e.message)}};
async function loadProviders(){try{const rows=await api('/api/providers');cards('providers',rows,x=>`<article><label>${x.available?'KULLANILABİLİR':'ULAŞILAMIYOR'}</label><h3>${esc(x.name)}</h3><p>Kayıtlı başarı: ${x.success_rate==null?'Henüz veri yok':x.success_rate+'%'}</p></article>`)}catch(e){toast(e.message)}}
async function loadObservability(view){try{if(view==='research'){const x=await api('/api/research');cards('researchCards',x.items,r=>`<article><label>${esc(r.status)}</label><h3>${esc(r.name)}</h3><p>${esc(r.provider||'Provider kaydı yok')} · ${esc(r.duration_seconds==null?'Süre kaydı yok':r.duration_seconds+' sn')}</p></article>`)}if(view==='aiProviders'){const rows=await api('/api/providers');cards('providerCards',rows,r=>`<article><div class="section-head"><label>${r.available?'AVAILABLE':'UNAVAILABLE'}</label><span class="badge ${r.available?'safe':'risk'}">${esc(r.resource_type||'Tür kaydı yok')}</span></div><h3>${esc(r.name)}</h3><p>Başarılı: ${r.successful_calls} · Başarısız: ${r.failed_calls} · Fallback: ${r.fallback_count}</p><p>Ortalama süre: ${esc(r.average_duration_seconds==null?'Henüz veri yok':r.average_duration_seconds+' sn')}<br>Son kullanım: ${esc(r.last_used_at||'Henüz veri yok')}</p></article>`)}if(view==='costs'){const x=await api('/api/costs');cards('costCards',[x],r=>`<article><label>${r.available?'ÖLÇÜLEN MALİYET':'VERİ YOK'}</label><h3>${esc(r.available?'Maliyet özeti':r.message)}</h3>${r.available?`<p>Bugün: ${esc(r.today)} ${esc(r.currency)} · 7 gün: ${esc(r.last_7_days)} ${esc(r.currency)}</p>`:'<p>Para miktarı tahmin edilmez veya uydurulmaz.</p>'}</article>`)}if(view==='systemLogs'){const rows=await api('/api/logs');cards('logCards',rows,r=>`<div class="event ${esc(r.severity)}"><span>${esc(r.timestamp||'—')}</span><b>${esc(r.component||'system')}</b><p>${esc(r.event||'')}</p></div>`)}}catch(e){toast(e.message)}}
window.workerAction=async(id,action)=>{try{await api(`/api/workers/${id}/${action}`,{});toast(`${id} · ${action}`);refresh()}catch(e){toast(e.message)}};
window.editSchedule=async(id,division)=>{const at=prompt('Local time (HH:MM), Europe/Berlin','10:00');if(at===null)return;const job=division==='YOUTUBE'?'PRODUCTION':division==='FINANCE'?'PAPER_RESEARCH':'OPERATIONS';try{await api(`/api/workers/${id}/schedule`,{enabled:true,timezone:'Europe/Berlin',jobs:[{job_type:job,days:[0,2,4],time:at}]});toast('Schedule enabled explicitly · Europe/Berlin');refresh()}catch(e){toast(e.message)}};
window.connectAccount=async id=>{try{const x=await api(`/api/accounts/${id}/connect`,{});location.assign(x.authorization_url)}catch(e){toast(e.message)}};
window.accountAction=async(id,action)=>{try{await api(`/api/accounts/${id}/${action}`,{});toast(action+' complete');refresh()}catch(e){toast(e.message)}};
window.workerDetail=async id=>{try{const w=await api('/api/workers/'+id),c=w.channel||{};cards('workerDetail',[w],x=>`<article><label>IDENTITY</label><h3>${esc(x.name)} · ${esc(x.role)}</h3><p>${esc(x.division)} · ${esc(c.market||x.finance_scope||'')} · ${esc(c.language||'')}</p><label>CURRENT WORK / WHY</label><p>${esc(x.current_goal||'—')}<br>${esc(x.current_task||'—')}</p><label>TOOLS / CAPABILITIES</label><p>${esc((x.capability_access||[]).join(' · '))}</p><label>MEMORY / LEARNING</label><p>${esc((x.learning_refs||[]).join(' · ')||'—')}</p><label>DECISIONS</label><p>${esc((x.decision_history||[]).slice(-5).map(d=>d.summary).join(' | ')||'—')}</p><label>ERRORS / RECOVERY</label><p>${esc(x.last_error||'None')}</p><label>ACCOUNT</label><p>${esc(c.identity?.status||'NOT CONNECTED')} · secrets never displayed</p></article>`)}catch(e){toast(e.message)}};
$('stopWorkers').onclick=async()=>{try{await api('/api/workers/stop-all',{});refresh()}catch(e){toast(e.message)}};
async function loadArtifacts(){try{const rows=await api('/api/artifacts');cards('artifactList',rows,x=>{const u='/artifact/'+encodeURI(x.path),preview=x.type.startsWith('video/')?`<video controls preload="metadata" src="${u}"></video>`:x.type.startsWith('image/')?`<img loading="lazy" src="${u}" alt="${esc(x.name)}">`:'';return `<article>${preview}<label>${esc(x.type)} · ${(x.size/1048576).toFixed(2)} MB</label><h3>${esc(x.name)}</h3><a href="${u}" target="_blank" rel="noopener">ARTIFACT'I AÇ</a></article>`})}catch(e){toast(e.message)}}
async function loadYoutubeArtifacts(){try{const rows=(await api('/api/artifacts')).filter(x=>x.type.startsWith('video/'));cards('youtubeArtifacts',rows,x=>{const u='/artifact/'+encodeURI(x.path);return `<article><video controls preload="metadata" src="${u}"></video><label>VIDEO READY · ${esc(x.type)}</label><h3>${esc(x.name)}</h3><p>Quality score: ${esc(x.quality_score??'metadata yok')}</p><a href="${u}" target="_blank" rel="noopener">ÖNİZLE</a></article>`})}catch(e){toast(e.message)}}
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(SpeechRecognition){const rec=new SpeechRecognition();rec.lang='tr-TR';rec.interimResults=false;rec.onstart=()=>{$('voiceStatus').textContent='Dinleniyor…'};rec.onresult=e=>{$('goal').value=e.results[0][0].transcript;$('voiceStatus').textContent='Komut algılandı; güvenli goal pipeline’a gönderiliyor.';command('voice')};rec.onerror=e=>$('voiceStatus').textContent='Ses algılama hatası: '+e.error;$('mic').onclick=()=>rec.start()}else{$('mic').disabled=true;$('voiceStatus').textContent='Bu browser ses algılamayı desteklemiyor; metin komutu kullanılabilir.'}
setInterval(refresh,7000);refresh();
